openapi: 3.0.1
info:
  title: Identidade e Acesso API
  description: API para cadastro de usuário, autenticação, e busca de informações do usuário.
  version: 1.0.0

servers:
  - url: https://localhost:3000/Prod
    description: Production environment

paths:
  /sign-up/:
    post:
      summary: Cadastro de um cliente.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: Carlos
                email:
                  type: string
                  example: carlos@gmail.com
                cpf:
                  type: string
                  example: 85362574125
                senha:
                  type: string
                  example: p4ssw0rd
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Usuário cadastrado com sucesso.

  /sign-in/:
    post:
      summary: Autenticação de um cliente.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: carlos@gmail.com
                senha:
                  type: string
                  example: p4ssw0rd
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  ChallengeParameters:
                    type: object
                    example: {}
                  AuthenticationResult:
                    type: object
                    properties:
                      AccessToken:
                        type: string
                        example: eyJraWQiOiJQVERydGZlTmtqTGI3SndVVzhFN...
                      ExpiresIn:
                        type: integer
                        example: 3600
                      TokenType:
                        type: string
                        example: Bearer
                      RefreshToken:
                        type: string
                        example: eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUl...
                      IdToken:
                        type: string
                        example: eyJraWQiOiJhQ2YzNUNHZmJ6VXpNd1I5eVZzbk80T3k5Kz...

  /user-info/:
    get:
      summary: Buscar dados cadastrais do cliente.
      security:
        - bearerAuth: []
      responses:
        200:
          description: Dados retornados com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: Carlos
                  cpf:
                    type: string
                    example: 37100223806
                  email:
                    type: string
                    example: carlos@gmail.com

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT