name: Delete SAM Stack

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Delete SAM Stack
      run: |
        aws cloudformation delete-stack --stack-name your-stack-name \
          --region us-east-1  # Replace with your AWS region