name: Deploy SAM Application

on:
  push:
    branches:
      - main  # or any branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials using the secrets stored in the GitHub repository
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install SAM CLI
      - name: Install AWS SAM CLI
        run: |
          sudo pip install aws-sam-cli

      # Deploy the SAM application
      - name: Deploy SAM Application
        run: |
          sam deploy
